description=A minimal multi-module project for scala 3 using clean architecture
name=My Project
organization=com.example
package=$organization$

sbt_version=maven(org.scala-sbt, sbt, stable)
scala_version=3.3.8
